# .gitlab-ci.yml

image: docker:latest

stages:
  - build
  - deploy
  - notifications

variables:
  REGISTRY: "docker.io"
  REGISTRY_USER: "robpco"
  RELEASE_IMAGE: "nginx-uwsgi"
  REGISTRY_IMAGE: "${REGISTRY}/${REGISTRY_USER}/${RELEASE_IMAGE}"
  DOCKER_DRIVER: overlay2

build27:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASSWORD"
    - docker build --pull --tag "${REGISTRY_IMAGE}:2.7" --tag "${REGISTRY_IMAGE}:py2.7" --tag "${REGISTRY_IMAGE}:python2.7" ./python2.7/
    - docker push "${REGISTRY_IMAGE}:2.7"
    - docker push "${REGISTRY_IMAGE}:py2.7"
    - docker push "${REGISTRY_IMAGE}:python2.7"
  only:
    variables:
      - $CI_COMMIT_TAG =~ /^deploy+/
  retry: 2
  tags: 
    - docker

build36:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASSWORD"
    - docker build --pull --tag "${REGISTRY_IMAGE}:3.6" --tag "${REGISTRY_IMAGE}:py3.6" --tag "${REGISTRY_IMAGE}:python3.6" ./python3.6/
    - docker push "${REGISTRY_IMAGE}:3.6"
    - docker push "${REGISTRY_IMAGE}:py3.6"
    - docker push "${REGISTRY_IMAGE}:python3.6"
  only:
    variables:
      - $CI_COMMIT_TAG =~ /^deploy+/
  retry: 2
  tags: 
    - docker

trigger_build:
  stage: deploy
  image: 
    name: robpco/awscli
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  script:
    - 'curl -X POST -F token="$TRIGGER_TOKEN" -F ref="master" -F "variables[CI_COMMIT_TAG]=deploy99" https://gitlab.com/api/v4/projects/7004817/trigger/pipeline'
  allow_failure: true
  only:
    variables:
      - $CI_COMMIT_TAG =~ /^deploy+/
  tags: 
    - docker

notify_succcess_slack:
  stage: notifications
  allow_failure: true
  script:
    - apk --update add curl
    - date=$(date +%Y%m%d-%H%M)
    - './.cicd/notify_slack.sh "#builds" "$RELEASE_IMAGE - build success at $date"'
  when: on_success
  only:
    variables:
      - $CI_COMMIT_TAG =~ /^deploy+/

notify_fail_slack:
  stage: notifications
  allow_failure: true
  script:
    - apk --update add curl 
    - date=$(date +%Y%m%d-%H%M)
    - './.cicd/notify_slack.sh "#builds" "$RELEASE_IMAGE - build failure at $date"'
  when: on_failure
  only:
    variables:
      - $CI_COMMIT_TAG =~ /^deploy+/